version: "2"
services:
  api:
    build: ./
    image: currency_api
    container_name: currency_api
    ports:
    - 3006:3006
    expose:
      - 3006
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: currency_mongo
    restart: always
    volumes:
    - './mongo:/data/db'
    ports:
    - 27018:27017
  nginx:
    image: nginx
    container_name: currency_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./nginx/mime.types:/etc/nginx/mime.types:ro
    ports:
    - 84:80
    depends_on:
      - api
